name: ci
on: push
jobs:
  test:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Switch Xcode to 11.5
        run: xcversion select 11.5
      - name: Resolve package dependencies
        run: swift package resolve
      - name: Test
        run: swift test --skip-update --parallel
